/* Problem tree viewer.
 *
 * Data: window.PROBLEM_DATA, generated by problems/build.py from problems/items/*.md,
 * tex-new/examples.tex and req/*.md. Markdown is rendered with marked, math with KaTeX,
 * and the graph with Cytoscape + dagre, all loaded from a CDN. Without them, text is
 * shown as plain source and the graph view says what is missing.
 */
(function () {
  "use strict";

  const DATA = window.PROBLEM_DATA;
  const app = document.getElementById("app");
  if (!DATA) {
    app.innerHTML = '<p class="empty">No data found. Run <code>python3 problems/build.py</code>, then reload.</p>';
    return;
  }
  if (window.marked) window.marked.use({ gfm: true });

  // ------------------------------------------------------------------ model

  const STATUS = {
    open: { label: "Open", rank: 0, help: "confirmed; no agreed fix yet" },
    decision: { label: "Needs decision", rank: 1, help: "the options are known; the team has to choose" },
    proposed: { label: "Fix proposed", rank: 2, help: "a solution is proposed but not applied yet" },
    resolved: { label: "Resolved", rank: 3, help: "fixed in the formalism, the examples or the parser" },
    closed: { label: "Not a problem", rank: 4, help: "turned out not to be a problem; kept as a record" },
  };
  const SOL_STATUS = {
    decision: { label: "Needs decision", rank: 0, cls: "decision", help: "one of several alternatives; the team has to choose" },
    proposed: { label: "Proposed", rank: 1, cls: "proposed", help: "ready to be applied" },
    applied: { label: "Applied", rank: 2, cls: "resolved", help: "already done" },
    rejected: { label: "Rejected", rank: 3, cls: "closed", help: "tried or considered, then dropped" },
  };
  const SEVERITY = {
    major: { label: "Major", rank: 0 },
    medium: { label: "Medium", rank: 1 },
    minor: { label: "Minor", rank: 2 },
  };
  const STATUS_KEYS = Object.keys(STATUS);
  const SOL_KEYS = Object.keys(SOL_STATUS);
  const UNRESOLVED = new Set(["open", "decision", "proposed"]);
  const ACTIVE_SOL = new Set(["decision", "proposed"]);
  // How a problem bears on the first goal: a full translation to the Event Calculus.
  const EC = {
    blocker: { label: "Blocks the translation", short: "Blocks it", rank: 0 },
    work: { label: "Work for the translator", short: "Translator work", rank: 1 },
    tooling: { label: "Needed to run the translation", short: "Needed to run it", rank: 2 },
    none: { label: "Does not affect the translation", short: "No effect", rank: 3 },
  };

  const items = DATA.items;
  const byId = new Map(items.map((it) => [it.id, it]));
  const problems = items.filter((it) => it.kind === "problem");
  const solutions = items.filter((it) => it.kind === "solution");
  const goal = items.find((it) => it.kind === "goal");
  const reqs = DATA.requirements;
  const reqById = new Map(reqs.map((r) => [r.id, r]));
  const reqBySlug = new Map(reqs.map((r) => [r.slug, r]));

  function compareItems(a, b) {
    if (a.kind !== b.kind) {
      const rank = { category: 0, problem: 1, solution: 2, goal: 3 };
      return rank[a.kind] - rank[b.kind];
    }
    if (a.kind === "category") return a.order - b.order || a.title.localeCompare(b.title);
    if (a.kind === "solution") {
      return SOL_STATUS[a.status].rank - SOL_STATUS[b.status].rank || a.title.localeCompare(b.title);
    }
    return (
      STATUS[a.status].rank - STATUS[b.status].rank ||
      SEVERITY[a.severity].rank - SEVERITY[b.severity].rank ||
      a.title.localeCompare(b.title)
    );
  }

  const kids = new Map();
  for (const it of items) {
    if (it.kind === "solution" || it.kind === "goal") continue;
    const p = it.parent || "";
    if (!kids.has(p)) kids.set(p, []);
    kids.get(p).push(it);
  }
  for (const list of kids.values()) list.sort(compareItems);
  const childrenOf = (id) => kids.get(id) || [];
  const roots = childrenOf("");
  const categories = roots.filter((x) => x.kind === "category");

  function ancestors(it) {
    const out = [];
    for (let p = it.parent; p && byId.has(p); p = byId.get(p).parent) out.unshift(byId.get(p));
    return out;
  }
  const categoryOf = (it) => ancestors(it)[0] || it;
  function descendants(it) {
    const out = [];
    (function walk(x) {
      for (const c of childrenOf(x.id)) {
        out.push(c);
        walk(c);
      }
    })(it);
    return out;
  }
  const directReqs = (it) => [...new Set(it.affects.filter((a) => a.req !== "all").map((a) => a.req))].sort();
  const affectsAll = (it) => it.affects.some((a) => a.req === "all");
  const affectsDirectly = (it, rid) => it.affects.some((a) => a.req === rid);
  const ecOpen = (p) => p.kind === "problem" && p.ec !== "none" && UNRESOLVED.has(p.status);
  const ecBlocking = (p) => p.kind === "problem" && p.ec === "blocker" && UNRESOLVED.has(p.status);
  const leadsTo = (p) => problems.filter((q) => q.causedBy.includes(p.id)).sort(compareItems);
  const subProblems = (p) => childrenOf(p.id).filter((c) => c.kind === "problem");
  const solutionsFor = (p) =>
    solutions.filter((s) => s.solves.includes(p.id) || s.partlySolves.includes(p.id)).sort(compareItems);
  const enables = (s) => solutions.filter((x) => x.needs.includes(s.id)).sort(compareItems);
  function alternativesOf(s) {
    const ids = new Set(s.alternativeTo);
    for (const x of solutions) if (x.alternativeTo.includes(s.id)) ids.add(x.id);
    return [...ids].map((id) => byId.get(id));
  }
  // Every problem a problem leads to, directly or through its consequences and sub-problems.
  function downstream(p) {
    const seen = new Set();
    const stack = [p];
    while (stack.length) {
      const x = stack.pop();
      for (const q of leadsTo(x).concat(subProblems(x))) {
        if (!seen.has(q.id)) {
          seen.add(q.id);
          stack.push(q);
        }
      }
    }
    return [...seen].map((id) => byId.get(id));
  }
  // Unresolved problems with no cause of their own that lead to other unresolved problems.
  function rootCauses() {
    return problems
      .filter((p) => UNRESOLVED.has(p.status) && !p.causedBy.length && byId.get(p.parent).kind === "category")
      .map((p) => ({ p, n: downstream(p).filter((q) => UNRESOLVED.has(q.status)).length }))
      .filter((x) => x.n > 0)
      .sort((a, b) => b.n - a.n || compareItems(a.p, b.p));
  }
  function rootCausesHtml(href) {
    return `<ul class="links roots">${rootCauses()
      .map(
        ({ p, n }) =>
          `<li>${dot(p)}<span><a href="${href(p)}">${esc(p.title)}</a> <span class="muted">· leads to ${n} other problem${n === 1 ? "" : "s"}</span></span></li>`
      )
      .join("")}</ul>`;
  }

  function countBy(list) {
    const c = {};
    for (const x of list) c[x.status] = (c[x.status] || 0) + 1;
    return c;
  }

  // ------------------------------------------------------------------ rich text

  const esc = (s) =>
    String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

  function mathHtml(tex, display) {
    if (window.katex) {
      try {
        return window.katex.renderToString(tex, { displayMode: display, throwOnError: false, strict: "ignore" });
      } catch (e) {
        /* fall back to the source */
      }
    }
    return display ? `<pre class="tex">${esc(tex)}</pre>` : `<code class="tex">${esc(tex)}</code>`;
  }

  // Markdown with $...$ and $$...$$ math. Code is set aside first, so that a $ in
  // code is not taken for math; math is set aside so that Markdown leaves it alone.
  function rich(md, inline) {
    if (!md) return "";
    const code = [];
    const math = [];
    let s = md.replace(/```[\s\S]*?```|`[^`\n]+`/g, (m) => {
      code.push(m);
      return `\u0000${code.length - 1}\u0000`;
    });
    s = s.replace(/\$\$([\s\S]+?)\$\$/g, (m, t) => {
      math.push([t, true]);
      return `MATHPH${math.length - 1}PH`;
    });
    s = s.replace(/\$([^$\n]+?)\$/g, (m, t) => {
      math.push([t, false]);
      return `MATHPH${math.length - 1}PH`;
    });
    s = s.replace(/\u0000(\d+)\u0000/g, (m, i) => code[Number(i)]);
    let html;
    if (window.marked) html = inline ? window.marked.parseInline(s) : window.marked.parse(s);
    else html = inline ? esc(s) : s.split(/\n{2,}/).map((p) => `<p>${esc(p)}</p>`).join("");
    return html.replace(/MATHPH(\d+)PH/g, (m, i) => mathHtml(math[Number(i)][0], math[Number(i)][1]));
  }

  // ------------------------------------------------------------------ small pieces

  // In the graph view, links select nodes in the graph; elsewhere they open the item.
  let graphLinks = false;
  const hrefItem = (it) =>
    graphLinks ? `#/g/${it.id}` : it.kind === "solution" ? `#/s/${it.id}` : it.kind === "goal" ? "#/" : `#/p/${it.id}`;
  const hrefReq = (r) => (graphLinks ? `#/g/${r.slug}` : `#/r/${r.slug}`);

  function dot(it) {
    if (it.kind === "category") return '<span class="dot cat"></span>';
    if (it.kind === "goal") return '<span class="dot goal" title="Goal"></span>';
    if (it.kind === "solution") {
      const st = SOL_STATUS[it.status];
      return `<span class="dot sol st-${st.cls}" title="Solution: ${esc(st.label)}"></span>`;
    }
    return `<span class="dot st-${it.status}" title="${esc(STATUS[it.status].label)}"></span>`;
  }
  function statusLabel(it) {
    if (it.kind === "solution") return SOL_STATUS[it.status].label;
    if (it.kind === "problem") return STATUS[it.status].label;
    return it.kind === "goal" ? "Goal" : "Category";
  }
  function badge(it) {
    if (it.kind === "solution") {
      const st = SOL_STATUS[it.status];
      return `<span class="badge st-${st.cls}">${esc(st.label)}</span><span class="badge kind">Solution</span>`;
    }
    return `<span class="badge st-${it.status}">${esc(STATUS[it.status].label)}</span>`;
  }
  function reqTags(it) {
    const nums = directReqs(it).map((r) => r.slice(4));
    let html = affectsAll(it) ? '<span class="rtag all" title="Affects every requirement">all</span>' : "";
    html += nums.slice(0, 4).map((n) => `<span class="rtag" title="Req ${n}">${n}</span>`).join("");
    if (nums.length > 4) {
      const rest = nums.slice(4).map((n) => "Req " + n).join(", ");
      html += `<span class="rtag" title="${esc(rest)}">+${nums.length - 4}</span>`;
    }
    return html;
  }
  function linkList(list, note) {
    if (!list.length) return "";
    return `<ul class="links">${list
      .map(
        (x) =>
          `<li>${dot(x)}<span><a href="${hrefItem(x)}">${esc(x.title)}</a> <span class="muted">· ${esc(
            statusLabel(x)
          )}${note ? note(x) : ""}</span></span></li>`
      )
      .join("")}</ul>`;
  }
  function nestedList(it) {
    const ch = childrenOf(it.id);
    if (!ch.length) return "";
    return `<ul class="links nested">${ch
      .map(
        (c) =>
          `<li>${dot(c)}<div><a href="${hrefItem(c)}">${esc(c.title)}</a> <span class="tags">${
            c.kind === "problem" ? reqTags(c) : ""
          }</span>${nestedList(c)}</div></li>`
      )
      .join("")}</ul>`;
  }
  function affectsHtml(it, title) {
    const head = `<h3>${esc(title)}</h3>`;
    if (!it.affects.length) return `<section>${head}<p class="muted">No current requirement or test.</p></section>`;
    const withTests = it.affects.some((a) => a.test);
    const rows = it.affects
      .map((a) => {
        const req =
          a.req === "all"
            ? '<span class="rchip all">All requirements</span>'
            : `<a class="rchip" href="${hrefReq(reqById.get(a.req))}">${esc(a.req)}</a>`;
        let test = "";
        if (a.test) {
          const t = ((reqById.get(a.req) || {}).tests || []).find((x) => x.id === a.test);
          test = `<span class="tchip"${t ? ` title="${esc(t.text)}"` : ""}>${esc(a.test)}</span>`;
        }
        return `<tr><td>${req}</td>${withTests ? `<td>${test}</td>` : ""}<td>${rich(a.note, true)}</td></tr>`;
      })
      .join("");
    return `<section>${head}<table class="affects"><thead><tr><th>Requirement</th>${
      withTests ? "<th>Test</th>" : ""
    }<th>How</th></tr></thead><tbody>${rows}</tbody></table></section>`;
  }
  const sections = (it) => it.sections.map((s) => `<section><h3>${esc(s.title)}</h3>${rich(s.body)}</section>`).join("");
  const graphLink = (id) => (graphLinks ? "" : `<a class="meta" href="#/g/${id}">Show in graph</a>`);

  function legendHtml() {
    const p = STATUS_KEYS.map(
      (k) => `<li>${dot({ kind: "problem", status: k })}<span><strong>${esc(STATUS[k].label)}</strong>: ${esc(STATUS[k].help)}</span></li>`
    ).join("");
    const s = SOL_KEYS.map(
      (k) => `<li>${dot({ kind: "solution", status: k })}<span><strong>${esc(SOL_STATUS[k].label)}</strong>: ${esc(SOL_STATUS[k].help)}</span></li>`
    ).join("");
    return `<section class="legend"><div><h3>Problems</h3><ul class="links">${p}</ul></div><div><h3>Solutions</h3><ul class="links">${s}</ul></div></section>`;
  }

  // ------------------------------------------------------------------ detail panes

  function problemDetail(it) {
    const crumbs = ancestors(it)
      .map((a) => `<a href="${hrefItem(a)}">${esc(a.title)}</a>`)
      .join(' <span class="sep">›</span> ');
    const sols = solutionsFor(it);
    const solHtml = sols.length
      ? linkList(sols, (s) => (s.partlySolves.includes(it.id) ? " · solves part of it" : ""))
      : '<p class="muted">No solution recorded yet.</p>';
    const causes = it.causedBy.map((id) => byId.get(id));
    const effects = leadsTo(it);
    const subs = subProblems(it);
    const shown = new Set([...causes, ...effects, ...subs].map((x) => x.id));
    const related = [
      ...it.related.map((id) => byId.get(id)),
      ...items.filter((x) => x.related.includes(it.id) && !it.related.includes(x.id)),
    ].filter((x) => !shown.has(x.id) && x.id !== it.parent);
    return `<article class="detail">
      <div class="crumbs">${crumbs}</div>
      <h2>${esc(it.title)}</h2>
      <div class="badges">${badge(it)}<span class="badge sev sev-${it.severity}">${esc(SEVERITY[it.severity].label)}</span>
        <span class="meta">Found ${esc(it.found)}</span>${graphLink(it.id)}</div>
      ${ecLine(it)}
      <div class="lead">${rich(it.summary)}</div>
      ${sections(it)}
      <section class="solbox"><h3>Solutions</h3>${solHtml}</section>
      ${affectsHtml(it, "Affected requirements and tests")}
      ${causes.length ? `<section><h3>Caused by</h3>${linkList(causes)}</section>` : ""}
      ${effects.length ? `<section><h3>Leads to</h3>${linkList(effects)}</section>` : ""}
      ${subs.length ? `<section><h3>Sub-problems</h3>${linkList(subs)}</section>` : ""}
      ${related.length ? `<section><h3>Related</h3>${linkList(related)}</section>` : ""}
      ${it.sources ? `<section><h3>Sources</h3>${rich(it.sources)}</section>` : ""}
      <p class="file">Edit: <code>${esc(it.file)}</code></p>
    </article>`;
  }

  function ecLine(p) {
    const done = !UNRESOLVED.has(p.status);
    const label = p.ec === "blocker" && done ? "Blocked it (resolved)" : EC[p.ec].short;
    return `<div class="ecline ec-${p.ec}${done ? " done" : ""}"><span class="eckey">EC translation</span><strong>${esc(
      label
    )}</strong><span class="ecwhy">${rich(p.ecWhy, true)}</span></div>`;
  }

  function solutionDetail(s) {
    const solves = s.solves.map((id) => byId.get(id)).sort(compareItems);
    const partly = s.partlySolves.map((id) => byId.get(id)).sort(compareItems);
    const needs = s.needs.map((id) => byId.get(id));
    const en = enables(s);
    const alts = alternativesOf(s);
    const n = solves.length + partly.length;
    return `<article class="detail">
      <div class="crumbs">Solution</div>
      <h2>${esc(s.title)}</h2>
      <div class="badges">${badge(s)}<span class="meta">solves ${solves.length}${
      partly.length ? ` and part of ${partly.length}` : ""
    } problem${n === 1 ? "" : "s"}</span>${graphLink(s.id)}</div>
      <div class="lead">${rich(s.summary)}</div>
      ${sections(s)}
      <section><h3>Solves</h3>${linkList(solves) || '<p class="muted">Nothing completely.</p>'}</section>
      ${partly.length ? `<section><h3>Solves in part</h3>${linkList(partly)}</section>` : ""}
      ${needs.length ? `<section><h3>Needs first</h3>${linkList(needs)}</section>` : ""}
      ${en.length ? `<section><h3>Enables</h3>${linkList(en)}</section>` : ""}
      ${alts.length ? `<section><h3>Alternatives (choose one)</h3>${linkList(alts)}</section>` : ""}
      ${affectsHtml(s, "Requirements and tests it changes")}
      ${s.sources ? `<section><h3>Sources</h3>${rich(s.sources)}</section>` : ""}
      <p class="file">Edit: <code>${esc(s.file)}</code></p>
    </article>`;
  }

  function categoryDetail(c) {
    const ps = descendants(c).filter((d) => d.kind === "problem");
    const cnt = countBy(ps);
    const stat = STATUS_KEYS.filter((k) => cnt[k])
      .map((k) => `<span>${dot({ kind: "problem", status: k })} ${cnt[k]} ${esc(STATUS[k].label.toLowerCase())}</span>`)
      .join("");
    return `<article class="detail">
      <div class="crumbs">Category</div>
      <h2>${esc(c.title)}</h2>
      <div class="lead">${rich(c.summary)}</div>
      <p class="statline">${stat}</p>
      <section><h3>Problems in this category</h3>${nestedList(c)}</section>
      <p class="file">Edit: <code>${esc(c.file)}</code></p>
    </article>`;
  }

  function goalDetail(g) {
    const open = problems.filter(ecOpen).sort((a, b) => EC[a.ec].rank - EC[b.ec].rank || compareItems(a, b));
    return `<article class="detail">
      <div class="crumbs">Goal</div>
      <h2>${esc(g.title)}</h2>
      <div class="badges"><span class="badge goal">Goal</span><span class="meta">${open.filter((p) => p.ec === "blocker").length} open blockers</span>${
      graphLinks ? '<a class="meta" href="#/">Open the EC translation view</a>' : graphLink(g.id)
    }</div>
      <div class="lead">${rich(g.summary)}</div>
      ${sections(g)}
      ${graphLinks ? '<p class="muted small">The graph shows only the problems in the way of the goal, and what leads to what among them. The solutions and the order to apply them are on the EC translation page.</p>' : ""}
      <section><h3>Still in the way</h3>${linkList(open, (p) => ` · ${esc(EC[p.ec].short.toLowerCase())}`)}</section>
    </article>`;
  }

  function itemDetail(id) {
    const it = byId.get(id);
    if (!it) return "";
    if (it.kind === "goal") return goalDetail(it);
    if (it.kind === "category") return categoryDetail(it);
    if (it.kind === "solution") return solutionDetail(it);
    return problemDetail(it);
  }

  function reqDetail(r) {
    const direct = problems.filter((p) => affectsDirectly(p, r.id)).sort(compareItems);
    const forAll = problems.filter(affectsAll).sort(compareItems);
    const sols = solutions.filter((s) => affectsDirectly(s, r.id)).sort(compareItems);
    const cnt = countBy(direct);
    const statBadges = STATUS_KEYS.filter((k) => cnt[k])
      .map((k) => `<span class="badge st-${k}">${cnt[k]} ${esc(STATUS[k].label.toLowerCase())}</span>`)
      .join("");
    const groups = STATUS_KEYS.map((k) => {
      const ps = direct.filter((p) => p.status === k);
      if (!ps.length) return "";
      const lis = ps
        .map((p) => {
          const notes = p.affects
            .filter((a) => a.req === r.id)
            .map((a) => (a.test ? `<span class="tchip">${esc(a.test)}</span> ` : "") + rich(a.note, true))
            .filter(Boolean);
          const cat = categoryOf(p);
          return `<li>${dot(p)}<span><a href="${hrefItem(p)}">${esc(p.title)}</a> <span class="muted">· ${esc(
            cat.short || cat.title
          )}</span>${notes.length ? `<span class="note">${notes.join(" · ")}</span>` : ""}</span></li>`;
        })
        .join("");
      return `<h4>${dot({ kind: "problem", status: k })} ${esc(STATUS[k].label)} <span class="muted">${ps.length}</span></h4><ul class="links probs">${lis}</ul>`;
    }).join("");

    let formal;
    if (!r.formalised) {
      formal = '<p class="muted">Not formalised yet.</p>';
    } else {
      const ent =
        r.entities && r.entities.rows.length
          ? `<table class="entities"><thead><tr>${r.entities.header.map((h) => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${r.entities.rows
              .map((row) => `<tr>${row.map((c) => `<td>${rich(c, true)}</td>`).join("")}</tr>`)
              .join("")}</tbody></table>`
          : "";
      formal = `${r.text ? `<div class="reqtext">${rich(r.text)}</div>` : ""}
        <p class="meta">Flavour: ${esc(r.flavour || "not declared")}</p>
        ${ent}
        ${r.definitions ? `<div class="defs">${rich(r.definitions)}</div>` : ""}
        ${r.constraint ? `<div class="constraint">${mathHtml(r.constraint, true)}</div>` : ""}
        ${r.notes ? `<div class="notes">${rich(r.notes)}</div>` : ""}`;
    }
    const tests = r.tests.length
      ? `<section><h3>Test cases</h3><ul class="tests">${r.tests
          .map((t) => `<li><span class="tchip">${esc(t.id)}</span> ${esc(t.text)}</li>`)
          .join("")}</ul></section>`
      : "";
    const files = [r.files.requirement, r.formalised ? "tex-new/examples.tex" : "", r.files.parser]
      .filter(Boolean)
      .map((f) => `<code>${esc(f)}</code>`)
      .join(", ");
    return `<article class="detail">
      <div class="crumbs">Requirement</div>
      <h2>${esc(r.id)}: ${esc(r.title)}</h2>
      <div class="badges">${statBadges || '<span class="meta">No problem names it directly</span>'}${graphLinks ? "" : `<a class="meta" href="#/g/${r.slug}">Show in graph</a>`}</div>
      <section><h3>Original text</h3><div class="original">${esc(r.original)}</div></section>
      <section><h3>Formalisation</h3>${formal}</section>
      ${tests}
      ${reqEcHtml(r)}
      <section><h3>Problems affecting this requirement</h3>${groups || '<p class="muted">None.</p>'}</section>
      ${sols.length ? `<section><h3>Solutions that change it</h3>${linkList(sols)}</section>` : ""}
      ${forAll.length ? `<section><h3>Problems affecting every requirement</h3>${linkList(forAll)}</section>` : ""}
      <p class="file">Files: ${files}</p>
    </article>`;
  }

  function reqEcHtml(r) {
    const specific = problems.filter((p) => ecBlocking(p) && affectsDirectly(p, r.id)).sort(compareItems);
    const general = problems.filter((p) => ecBlocking(p) && affectsAll(p)).sort(compareItems);
    const verdict =
      specific.length || general.length
        ? `<p class="ecverdict no">Not yet translatable: ${specific.length} blocker${specific.length === 1 ? "" : "s"} of its own, and ${general.length} that block every requirement.</p>`
        : '<p class="ecverdict yes">Nothing blocks its translation.</p>';
    return `<section class="ecbox${specific.length || general.length ? "" : " ok"}"><h3>Translation to the Event Calculus</h3>${verdict}
      ${specific.length ? `<h4>Its own blockers</h4>${linkList(specific)}` : ""}
      ${general.length ? `<h4>Blockers of every requirement</h4>${linkList(general)}` : ""}</section>`;
  }

  function allReqDetail() {
    const ps = problems.filter(affectsAll).sort(compareItems);
    return `<article class="detail"><div class="crumbs">Requirement</div><h2>All requirements</h2>
      <div class="lead"><p>Problems that concern every requirement, rather than particular ones.</p></div>
      <section><h3>Problems</h3>${linkList(ps)}</section></article>`;
  }

  // ------------------------------------------------------------------ overview

  // What a solution makes possible: the unresolved problems solved by it and by every
  // open solution that needs it, directly or indirectly, weighted by severity.
  const WEIGHT = { major: 3, medium: 2, minor: 1 };
  function impact(s) {
    const seen = new Set([s.id]);
    const stack = [s];
    const solved = new Set();
    while (stack.length) {
      const x = stack.pop();
      for (const id of x.solves.concat(x.partlySolves)) solved.add(id);
      for (const e of enables(x)) {
        if (ACTIVE_SOL.has(e.status) && !seen.has(e.id)) {
          seen.add(e.id);
          stack.push(e);
        }
      }
    }
    let weight = 0;
    for (const id of solved) {
      const p = byId.get(id);
      if (UNRESOLVED.has(p.status)) weight += WEIGHT[p.severity];
    }
    return { weight, unlocks: seen.size - 1 };
  }

  // Open solutions in an order that respects "needs"; among the ready ones,
  // those with the largest impact come first.
  function roadmap() {
    const active = solutions.filter((s) => ACTIVE_SOL.has(s.status));
    const ids = new Set(active.map((s) => s.id));
    const waiting = new Map(active.map((s) => [s.id, s.needs.filter((n) => ids.has(n)).length]));
    const score = new Map(active.map((s) => [s.id, impact(s).weight]));
    const ready = active.filter((s) => waiting.get(s.id) === 0);
    const order = [];
    while (ready.length) {
      ready.sort((a, b) => score.get(b.id) - score.get(a.id) || a.title.localeCompare(b.title));
      const s = ready.shift();
      order.push(s);
      for (const e of enables(s)) {
        if (!ids.has(e.id)) continue;
        waiting.set(e.id, waiting.get(e.id) - 1);
        if (waiting.get(e.id) === 0) ready.push(e);
      }
    }
    return order;
  }

  function overviewHtml() {
    const pc = countBy(problems);
    const sc = countBy(solutions);
    const pCards = STATUS_KEYS.map(
      (k) =>
        `<a class="card st-${k}" href="#/problems?status=${k}"><span class="num">${pc[k] || 0}</span><span class="lbl">${esc(
          STATUS[k].label
        )}</span></a>`
    ).join("");
    const sCards = SOL_KEYS.map(
      (k) =>
        `<a class="card st-${SOL_STATUS[k].cls}" href="#/solutions"><span class="num">${sc[k] || 0}</span><span class="lbl">${esc(
          SOL_STATUS[k].label
        )}</span></a>`
    ).join("");

    const order = roadmap();
    const step = new Map(order.map((s, i) => [s.id, i + 1]));
    const steps = order
      .map((s) => {
        const solved = s.solves.map((id) => byId.get(id)).filter((p) => UNRESOLVED.has(p.status));
        const majors = solved.filter((p) => p.severity === "major").length;
        const needs = s.needs.filter((n) => step.has(n)).map((n) => step.get(n));
        const alts = alternativesOf(s).filter((a) => step.has(a.id)).map((a) => step.get(a.id));
        const unlocks = impact(s).unlocks;
        const facts = [
          `solves ${solved.length}${s.partlySolves.length ? ` (+${s.partlySolves.length} in part)` : ""}${majors ? `, ${majors} major` : ""}`,
          unlocks ? `unlocks ${unlocks} later step${unlocks === 1 ? "" : "s"}` : "",
          needs.length ? `after step ${needs.join(", ")}` : "",
          alts.length ? `alternative to step ${alts.join(", ")}` : "",
        ].filter(Boolean);
        return `<li><span class="stepno">${step.get(s.id)}</span>${dot(s)}<div><a href="#/s/${s.id}">${esc(s.title)}</a>
          <span class="muted"> · ${esc(SOL_STATUS[s.status].label)} · ${facts.join(" · ")}</span></div></li>`;
      })
      .join("");

    const unresolvedIn = (cat, pred) =>
      descendants(cat).filter((d) => d.kind === "problem" && UNRESOLVED.has(d.status) && pred(d));
    const cell = (ps, href) => {
      const n = ps.length;
      const heat = n === 0 ? "" : n === 1 ? "h1" : n === 2 ? "h2" : "h3";
      const tip = ps.map((p) => "• " + p.title).join("\n");
      return `<td class="${heat}">${n ? `<a href="${href}" title="${esc(tip)}">${n}</a>` : ""}</td>`;
    };
    const head = `<tr><th class="left">Requirement</th>${categories
      .map((c) => `<th><a href="#/p/${c.id}" title="${esc(c.title)}">${esc(c.short || c.title)}</a></th>`)
      .join("")}<th>Total</th></tr>`;
    const perAll = categories.map((c) => unresolvedIn(c, affectsAll));
    const allRow = `<tr class="allrow"><th class="left"><a href="#/g/req-all">All requirements</a></th>${perAll
      .map((ps, i) => cell(ps, `#/p/${categories[i].id}`))
      .join("")}<td class="total">${perAll.reduce((a, x) => a + x.length, 0)}</td></tr>`;
    const rows = reqs
      .map((r) => {
        const per = categories.map((c) => unresolvedIn(c, (p) => affectsDirectly(p, r.id)));
        const total = per.reduce((a, x) => a + x.length, 0);
        return `<tr><th class="left"><a href="#/r/${r.slug}">${esc(r.id)}</a> <span class="muted">${esc(r.title)}</span></th>${per
          .map((ps) => cell(ps, `#/r/${r.slug}`))
          .join("")}<td class="total">${total}</td></tr>`;
      })
      .join("");

    return `<div class="overview">
      <section class="intro">
        <h2>Problems found in the formalism, and how to solve them</h2>
        <p>Every problem found so far, with an example, the affected requirements and test cases, and at least one proposed solution.
          <a href="#/">EC translation</a> shows what blocks the first goal; <a href="#/graph">Graph</a> shows what leads to what; <a href="#/problems">Problems</a> lists them by concept;
          <a href="#/solutions">Solutions</a> lists the proposed changes; <a href="#/requirements">Requirements</a> shows each requirement with its problems.</p>
      </section>
      <a class="goalbanner" href="#/"><span class="dot goal"></span><span><strong>First goal: translate to the Event Calculus.</strong>
        ${problems.filter(ecBlocking).length} problems block it. See what blocks it and in which order to remove it.</span></a>
      <div class="cardrow"><h3 class="sect">Problems</h3><div class="cards">${pCards}</div></div>
      <section>
        <h3 class="sect">Root causes</h3>
        <p class="muted small">Unresolved problems that other problems follow from. Click one to see in the graph what it leads to and what solves it.</p>
        ${rootCausesHtml((p) => `#/g/${p.id}`)}
      </section>
      <div class="cardrow"><h3 class="sect">Solutions</h3><div class="cards">${sCards}</div></div>
      <section>
        <h3 class="sect">Suggested order of the open solutions</h3>
        <p class="muted small">Each step only needs the steps before it. Among the steps that are ready, those that solve or unlock the most (weighted by severity) come first.</p>
        <ol class="roadmap">${steps}</ol>
      </section>
      <section>
        <h3 class="sect">Unresolved problems per requirement and category</h3>
        <p class="muted small">Counts problems that are open, need a decision or have a proposed fix. Hover a number to see the problems; click it to open the requirement.</p>
        <div class="matrix-wrap"><table class="matrix"><thead>${head}</thead><tbody>${allRow}${rows}</tbody></table></div>
      </section>
      ${legendHtml()}
    </div>`;
  }

  // ------------------------------------------------------------------ EC translation view

  // What a planned solution does for the translation: the problems in its way that are
  // solved by the solution and by every planned solution that needs it, weighted by severity.
  function ecImpact(s, planIds) {
    const seen = new Set([s.id]);
    const stack = [s];
    const solved = new Set();
    while (stack.length) {
      const x = stack.pop();
      for (const id of x.solves.concat(x.partlySolves)) solved.add(id);
      for (const e of enables(x)) {
        if (planIds.has(e.id) && !seen.has(e.id)) {
          seen.add(e.id);
          stack.push(e);
        }
      }
    }
    let weight = 0;
    for (const id of solved) if (ecOpen(byId.get(id))) weight += WEIGHT[byId.get(id).severity];
    return weight;
  }

  // The open solutions that solve a problem in the way of the translation, with everything
  // they need first, as ordered steps. Alternatives form one step (choose one). A step only
  // needs the steps before it. Among the ready steps, those that remove a blocker come before
  // those that only build, and then the largest impact comes first.
  function ecPlan() {
    const plan = new Map();
    const add = (s) => {
      if (plan.has(s.id) || !ACTIVE_SOL.has(s.status)) return;
      plan.set(s.id, s);
      for (const n of s.needs) add(byId.get(n));
    };
    for (const s of solutions) if (s.solves.concat(s.partlySolves).some((id) => ecOpen(byId.get(id)))) add(s);
    const ids = new Set(plan.keys());
    const score = new Map([...plan.values()].map((s) => [s.id, ecImpact(s, ids)]));
    const groupOf = new Map();
    const groups = [];
    for (const s of plan.values()) {
      if (groupOf.has(s.id)) continue;
      const g = { members: [], needs: new Set() };
      const stack = [s];
      while (stack.length) {
        const x = stack.pop();
        if (groupOf.has(x.id)) continue;
        groupOf.set(x.id, g);
        g.members.push(x);
        for (const a of alternativesOf(x)) if (ids.has(a.id)) stack.push(a);
      }
      g.members.sort((a, b) => score.get(b.id) - score.get(a.id) || compareItems(a, b));
      g.build = !g.members.some((x) => x.solves.concat(x.partlySolves).some((id) => ecBlocking(byId.get(id))));
      groups.push(g);
    }
    for (const g of groups) {
      for (const s of g.members) for (const n of s.needs) if (ids.has(n) && groupOf.get(n) !== g) g.needs.add(groupOf.get(n));
    }
    const gscore = (g) => score.get(g.members[0].id);
    const waiting = new Map(groups.map((g) => [g, g.needs.size]));
    const ready = groups.filter((g) => !g.needs.size);
    const order = [];
    while (ready.length) {
      ready.sort((a, b) => a.build - b.build || gscore(b) - gscore(a) || a.members[0].title.localeCompare(b.members[0].title));
      const g = ready.shift();
      order.push(g);
      for (const h of groups) {
        if (!h.needs.has(g)) continue;
        waiting.set(h, waiting.get(h) - 1);
        if (!waiting.get(h)) ready.push(h);
      }
    }
    for (const g of groups) if (!order.includes(g)) order.push(g);
    return order;
  }

  // The plan step that first removes a problem, or Infinity.
  const firstStep = (p, stepOf) => Math.min(Infinity, ...solutionsFor(p).filter((s) => stepOf.has(s.id)).map((s) => stepOf.get(s.id)));
  const byStep = (stepOf) => (a, b) => firstStep(a, stepOf) - firstStep(b, stepOf) || compareItems(a, b);

  // A problem in the way of the translation, with the open blockers that are part of it.
  // Each solution shows its step in the plan.
  function ecCard(p, stepOf, parentSols) {
    const link = (x) => `<a href="${hrefItem(x)}">${esc(x.title)}</a>`;
    const causes = p.causedBy.map((id) => byId.get(id)).filter((c) => UNRESOLVED.has(c.status));
    const sols = solutionsFor(p)
      .filter((s) => s.status !== "rejected")
      .sort((a, b) => (stepOf.get(a.id) || Infinity) - (stepOf.get(b.id) || Infinity) || compareItems(a, b));
    const same = parentSols && sols.length && sols.length === parentSols.length && sols.every((s) => parentSols.includes(s));
    const chip = (s) =>
      `<a class="solchip" href="${hrefItem(s)}" title="${esc(SOL_STATUS[s.status].label)}${stepOf.has(s.id) ? ` · step ${stepOf.get(s.id)} of the plan` : ""}">${
        stepOf.has(s.id) ? `<span class="stepno small">${stepOf.get(s.id)}</span>` : dot(s)
      }<span>${esc(s.title)}</span></a>`;
    const solHtml = same
      ? '<span class="muted small">Solved with the problem it is part of.</span>'
      : sols.length
      ? `<span class="eckey">Solved by</span>${sols.map(chip).join("")}`
      : '<span class="muted small">No solution yet.</span>';
    const subs = childrenOf(p.id).filter(ecBlocking).sort(byStep(stepOf));
    return `<div class="eccard st-${p.status}">
      <div class="echead">${dot(p)}${link(p)}<span class="tags">${reqTags(p)}</span></div>
      <div class="ecmeta">${esc(STATUS[p.status].label)} · <span class="sevtext sev-${p.severity}">${esc(SEVERITY[p.severity].label)}</span>${
      p.ec === "blocker" ? "" : ` · ${esc(EC[p.ec].label)}`
    }</div>
      <p class="ecwhy">${rich(p.ecWhy, true)}</p>
      ${causes.length ? `<p class="ecfrom">Follows from: ${causes.map(link).join("; ")}.</p>` : ""}
      <div class="ecsols">${solHtml}</div>
      ${subs.map((q) => ecCard(q, stepOf, sols)).join("")}
    </div>`;
  }

  function ecViewHtml() {
    const g = goal || { id: "", title: "Translate every requirement and test case into the Event Calculus", summary: "" };
    const blockers = problems.filter((p) => p.ec === "blocker");
    const open = blockers.filter(ecBlocking);
    const resolved = blockers.filter((p) => !UNRESOLVED.has(p.status)).sort(compareItems);
    const work = problems.filter((p) => ecOpen(p) && p.ec !== "blocker");
    const plink = (p) => `<a href="${hrefItem(p)}">${esc(p.title)}</a>`;
    const plan = ecPlan();
    const stepOf = new Map();
    plan.forEach((st, i) => st.members.forEach((s) => stepOf.set(s.id, i + 1)));

    const groupsHtml = categories
      .map((c) => {
        const inCat = open.filter((p) => categoryOf(p).id === c.id);
        const top = inCat.filter((p) => !ecBlocking(byId.get(p.parent))).sort(byStep(stepOf));
        if (!top.length) return "";
        return `<div class="ecgroup"><h4><a href="${hrefItem(c)}">${esc(c.title)}</a><span class="count" title="Open blockers">${
          inCat.length
        }</span></h4>${top.map((p) => ecCard(p, stepOf)).join("")}</div>`;
      })
      .join("");

    const stepsHtml = plan
      .map((st, i) => {
        const after = [...new Set(st.members.flatMap((s) => s.needs.filter((n) => stepOf.has(n)).map((n) => stepOf.get(n))))]
          .filter((n) => n !== i + 1)
          .sort((a, b) => a - b);
        const opts = st.members
          .map((s) => {
            const full = s.solves.map((id) => byId.get(id)).filter(ecOpen);
            const part = s.partlySolves.map((id) => byId.get(id)).filter(ecOpen);
            const what =
              [full.length ? `Removes ${full.map(plink).join("; ")}.` : "", part.length ? `Removes part of ${part.map(plink).join("; ")}.` : ""]
                .filter(Boolean)
                .join(" ") || "Removes nothing by itself; later steps need it.";
            return `<div class="opt">${dot(s)}<div><a class="otitle" href="${hrefItem(s)}">${esc(s.title)}</a> <span class="muted small">· ${esc(
              SOL_STATUS[s.status].label
            )}</span><div class="stepnote">${what}</div></div></div>`;
          })
          .join(st.members.length > 1 ? '<div class="or">or</div>' : "");
        const head =
          i === 0 && !st.build
            ? '<li class="ecphase">First, decide and fix what blocks it</li>'
            : st.build && plan.slice(i).every((x) => x.build) && (i === 0 || !plan[i - 1].build)
            ? '<li class="ecphase">Then build the translator</li>'
            : "";
        return `${head}<li class="ecstep"><span class="stepno">${i + 1}</span><div>${st.members.length > 1 ? '<div class="choose">Choose one</div>' : ""}${opts}${
          after.length ? `<div class="stepafter">After step ${after.join(", ")}</div>` : ""
        }</div></li>`;
      })
      .join("");

    const decisions = plan.map((st, i) => ({ st, i })).filter(({ st }) => st.members.some((s) => s.status === "decision"));
    const decideHtml = decisions.length
      ? `<div class="ecdecide"><strong>Waiting for a team decision</strong><ul>${decisions
          .map(
            ({ st, i }) =>
              `<li><span class="stepno small" title="Step ${i + 1} of the plan">${i + 1}</span><span>${st.members
                .map((s) => `<a href="${hrefItem(s)}">${esc(s.title)}</a>`)
                .join(" <em>or</em> ")}</span></li>`
          )
          .join("")}</ul></div>`
      : "";

    const ecSort = (a, b) => EC[a.ec].rank - EC[b.ec].rank || compareItems(a, b);
    const reqItem = (p, r) => {
      const named = r ? [...new Set(p.affects.filter((a) => a.req === r.id && a.test).map((a) => a.test))] : [];
      const tests =
        named.length && named.length === r.tests.length
          ? '<span class="tchip">all tests</span>'
          : named.map((t) => `<span class="tchip">${esc(t)}</span>`).join(" ");
      return `<li>${dot(p)}<span>${plink(p)}${p.ec === "blocker" ? "" : ` <span class="muted">· ${esc(EC[p.ec].short.toLowerCase())}</span>`}${
        tests ? " " + tests : ""
      }</span></li>`;
    };
    const general = problems.filter((p) => ecOpen(p) && affectsAll(p)).sort(ecSort);
    const reqRows = reqs
      .map((r) => {
        const own = problems.filter((p) => ecOpen(p) && affectsDirectly(p, r.id)).sort(ecSort);
        return `<tr><th><a href="#/r/${r.slug}">${esc(r.id)}</a><span class="muted">${esc(r.title)}</span></th><td>${
          own.length
            ? `<ul class="links">${own.map((p) => reqItem(p, r)).join("")}</ul>`
            : '<span class="muted">Nothing of its own; only the problems in the first row.</span>'
        }</td></tr>`;
      })
      .join("");

    const none = problems.filter((p) => p.ec === "none" && UNRESOLVED.has(p.status)).sort(compareItems);
    const noneHtml = none
      .map((p) => `<li>${dot(p)}<span>${plink(p)} <span class="muted">· ${esc(categoryOf(p).short || categoryOf(p).title)}</span><span class="note">${rich(p.ecWhy, true)}</span></span></li>`)
      .join("");
    const resolvedHtml = resolved.map((p) => `<li>${dot(p)}<span>${plink(p)}<span class="note">${rich(p.ecWhy, true)}</span></span></li>`).join("");

    work.sort(byStep(stepOf));
    const pct = blockers.length ? Math.round((100 * resolved.length) / blockers.length) : 100;
    const nDecision = open.filter((p) => p.status === "decision").length;
    return `<div class="ecview">
      <section class="echero">
        <div class="eyebrow">First goal</div>
        <h2>${esc(g.title)}</h2>
        <div class="lead">${rich(g.summary)}</div>
        <div class="ecprogress"><div class="ecbar" role="progressbar" aria-label="Blockers resolved" aria-valuemin="0" aria-valuemax="${
          blockers.length
        }" aria-valuenow="${resolved.length}"><span style="width: ${pct}%"></span></div>
          <span class="muted small">${resolved.length} of ${blockers.length} blockers resolved</span></div>
        <div class="cards">
          <div class="card st-open"><span class="num">${open.length}</span><span class="lbl">open blockers</span></div>
          <div class="card st-decision"><span class="num">${nDecision}</span><span class="lbl">of them wait for a team decision</span></div>
          <div class="card ec-work"><span class="num">${work.length}</span><span class="lbl">things to build or set up</span></div>
          <div class="card st-proposed"><span class="num">${plan.length}</span><span class="lbl">steps that remove all of them</span></div>
        </div>
        <p class="eclinks">${g.id ? `<a href="#/g/${g.id}">Show as a graph</a> · ` : ""}<a href="#/problems?ec=blocker&amp;status=open,decision,proposed">Show the blockers in the problem tree</a></p>
        ${decideHtml}
      </section>
      <div class="ecgrid">
        <div>
          <section>
            <h3 class="sect">What blocks the translation</h3>
            <p class="muted small">A problem blocks the translation when some requirement or test case cannot be written in the Event Calculus until the problem is decided. Example: until the formalism says whether a test case stands for one trace or for every trace it allows, we cannot say which <code>Happens</code> facts a test case becomes. Problems are grouped by concept and, within a concept, follow the plan on the right; the problems that are part of another one are shown inside it. The small numbers on the right of a problem are the requirements it affects; the numbered circles are steps of the plan.</p>
            ${groupsHtml || '<p class="muted">Nothing blocks the translation.</p>'}
          </section>
          <section>
            <h3 class="sect">What has to be built or set up</h3>
            <p class="muted small">Not decisions but work: the translation rules need the decisions above, and the translator needs the rules and the tools.</p>
            ${work.map((p) => ecCard(p, stepOf)).join("") || '<p class="muted">Nothing left to build.</p>'}
          </section>
        </div>
        <section class="ecplanbox">
          <h3 class="sect">How to unblock it</h3>
          <p class="muted small">The open solutions that remove these problems, with everything they need first. Each step needs only the steps before it; among the steps that are ready, the one that removes the most (counting what it unlocks, weighted by severity) comes first.</p>
          <ol class="ecplan">${stepsHtml}</ol>
        </section>
      </div>
      <section>
        <h3 class="sect">Which requirements can be translated</h3>
        <p class="muted small">None yet: the problems in the first row are in the way of every requirement. Once they are solved, a requirement can be translated when the problems in its own row are solved too. Grey chips name the test cases a problem affects.</p>
        <div class="ecreqs-wrap"><table class="ecreqs"><thead><tr><th>Requirement</th><th>In its way</th></tr></thead><tbody>
          <tr class="allrow"><th>All requirements</th><td><ul class="links">${general.map((p) => reqItem(p)).join("")}</ul></td></tr>
          ${reqRows}
        </tbody></table></div>
      </section>
      ${
        resolved.length
          ? `<section><h3 class="sect">Blockers already resolved</h3><ul class="links ecnotes">${resolvedHtml}</ul></section>`
          : ""
      }
      <section>
        <details class="ecnone"><summary>${none.length} unresolved problems do not affect the translation</summary>
          <p class="muted small">They are real problems, but the translation can be written without solving them. Each says why.</p>
          <ul class="links ecnotes">${noneHtml}</ul></details>
      </section>
    </div>`;
  }

  // ------------------------------------------------------------------ problems view (tree)

  const tstate = { search: "", statuses: new Set(STATUS_KEYS), req: "", ec: "", collapsed: new Set() };

  function matches(it) {
    if (it.kind !== "problem") return false;
    if (!tstate.statuses.has(it.status)) return false;
    if (tstate.req && !affectsDirectly(it, tstate.req) && !affectsAll(it)) return false;
    if (tstate.ec === "blocker" && it.ec !== "blocker") return false;
    if (tstate.ec === "relevant" && it.ec === "none") return false;
    if (tstate.search) {
      const hay = [it.title, it.summary, it.sources, ...it.sections.map((s) => s.body), ...it.affects.map((a) => `${a.req} ${a.test} ${a.note}`)]
        .join(" ")
        .toLowerCase();
      for (const w of tstate.search.toLowerCase().split(/\s+/).filter(Boolean)) if (!hay.includes(w)) return false;
    }
    return true;
  }

  function visibleIds() {
    const vis = new Set();
    (function walk(list) {
      let any = false;
      for (const it of list) {
        const sub = walk(childrenOf(it.id));
        if (matches(it) || sub) {
          vis.add(it.id);
          any = true;
        }
      }
      return any;
    })(roots);
    return vis;
  }

  function treeHtml(selected) {
    const vis = visibleIds();
    function node(it) {
      if (!vis.has(it.id)) return "";
      const ch = childrenOf(it.id).filter((c) => vis.has(c.id));
      const open = !tstate.collapsed.has(it.id) || tstate.search !== "";
      const caret = ch.length
        ? `<button class="caret" data-toggle="${it.id}" aria-expanded="${open}" aria-label="${open ? "Collapse" : "Expand"}">${open ? "▾" : "▸"}</button>`
        : '<span class="caret-space"></span>';
      const sel = it.id === selected ? " sel" : "";
      let row;
      if (it.kind === "category") {
        const n = descendants(it).filter((d) => d.kind === "problem" && UNRESOLVED.has(d.status) && vis.has(d.id)).length;
        row = `<div class="row cat${sel}">${caret}<a class="label" href="#/p/${it.id}">${esc(it.title)}</a><span class="count" title="Unresolved problems shown">${n}</span></div>`;
      } else {
        row = `<div class="row prob${sel}${matches(it) ? "" : " context"}">${caret}${dot(it)}<a class="label" href="#/p/${it.id}">${esc(
          it.title
        )}</a><span class="tags">${ecOpen(it) ? `<span class="ectag ec-${it.ec}" title="${esc(EC[it.ec].label)}">EC</span>` : ""}${reqTags(it)}</span></div>`;
      }
      return `<li>${row}${ch.length && open ? `<ul>${ch.map(node).join("")}</ul>` : ""}</li>`;
    }
    const html = roots.map(node).join("");
    return html ? `<ul class="tree">${html}</ul>` : '<p class="empty">No problem matches these filters.</p>';
  }

  function chipsHtml() {
    const counts = countBy(problems);
    return STATUS_KEYS.map(
      (k) =>
        `<button class="chip${tstate.statuses.has(k) ? " on" : ""}" data-status="${k}" aria-pressed="${tstate.statuses.has(k)}">${dot({
          kind: "problem",
          status: k,
        })}${esc(STATUS[k].label)}<span class="n">${counts[k] || 0}</span></button>`
    ).join("");
  }

  function toolbarHtml() {
    const opts = ['<option value="">Affecting any requirement</option>']
      .concat(reqs.map((r) => `<option value="${esc(r.id)}"${tstate.req === r.id ? " selected" : ""}>${esc(r.id)}: ${esc(r.title)}</option>`))
      .join("");
    return `<div class="toolbar">
      <input type="search" id="q" placeholder="Search problems" aria-label="Search problems" value="${esc(tstate.search)}">
      <div class="chips" id="chips">${chipsHtml()}</div>
      <select id="ecsel" aria-label="Effect on the Event Calculus translation">
        <option value=""${tstate.ec === "" ? " selected" : ""}>All problems</option>
        <option value="blocker"${tstate.ec === "blocker" ? " selected" : ""}>Only problems that block the EC translation</option>
        <option value="relevant"${tstate.ec === "relevant" ? " selected" : ""}>Only problems that matter for the EC translation</option>
      </select>
      <div class="toolrow">
        <select id="reqsel" aria-label="Only problems affecting this requirement">${opts}</select>
        <button class="link" id="expand">Expand all</button>
        <button class="link" id="collapse">Collapse all</button>
      </div>
    </div>`;
  }

  function placeholder(title, text, extra) {
    return `<div class="placeholder"><h2>${esc(title)}</h2><p>${esc(text)}</p>${extra || ""}</div>`;
  }

  // ------------------------------------------------------------------ graph view

  const gstate = { solutions: true, reqs: true, goal: true, done: false, parts: true, focus: true, mode: "both" };
  let cy = null;
  let gselected = "";
  let fullPositions = null;

  function graphNode(id, label, kind, statusCls, tip) {
    const width = kind === "req" ? 168 : 224;
    const chars = kind === "req" ? 21 : 28;
    const lines = label.split("\n").reduce((n, part) => n + Math.max(1, Math.ceil(part.length / chars)), 0);
    return {
      data: { id, label, kind, tip, w: width, h: 16 + lines * 17 },
      classes: `${kind}${statusCls ? " s-" + statusCls : ""}`,
    };
  }

  function graphElements() {
    const nodes = [];
    const edges = [];
    const vis = new Set();
    for (const p of problems) {
      if (!gstate.done && !UNRESOLVED.has(p.status)) continue;
      vis.add(p.id);
      nodes.push(graphNode(p.id, p.title, "problem", p.status, `Problem · ${STATUS[p.status].label} · ${SEVERITY[p.severity].label}`));
    }
    if (gstate.solutions) {
      for (const s of solutions) {
        if (!gstate.done && !ACTIVE_SOL.has(s.status)) continue;
        vis.add(s.id);
        nodes.push(graphNode(s.id, s.title, "solution", SOL_STATUS[s.status].cls, `Solution · ${SOL_STATUS[s.status].label}`));
      }
    }
    if (gstate.reqs) {
      for (const r of reqs) {
        vis.add(r.slug);
        nodes.push(graphNode(r.slug, `${r.id}\n${r.title}`, "req", "", "Requirement"));
      }
      vis.add("req-all");
      nodes.push(graphNode("req-all", "All requirements", "req", "", "Requirement"));
    }
    if (gstate.goal && goal) {
      vis.add(goal.id);
      nodes.push(graphNode(goal.id, `Goal: ${goal.title}`, "goal", "", "Goal"));
    }
    let n = 0;
    const edge = (a, b, cls) => {
      if (vis.has(a) && vis.has(b)) edges.push({ data: { id: `e${n++}`, source: a, target: b }, classes: cls });
    };
    for (const p of problems) {
      // Only the last problems of a chain point to the goal; the others reach it through them.
      const next = leadsTo(p).concat(gstate.parts ? subProblems(p) : []);
      if (goal && ecOpen(p) && !next.some(ecOpen)) edge(p.id, goal.id, p.ec === "blocker" ? "blocks" : "needed");
      for (const c of p.causedBy) edge(c, p.id, "cause");
      if (gstate.parts && p.parent && byId.get(p.parent).kind === "problem") edge(p.parent, p.id, "part");
      if (gstate.reqs) {
        for (const r of directReqs(p)) edge(p.id, reqById.get(r).slug, "affects");
        if (affectsAll(p)) edge(p.id, "req-all", "affects");
      }
    }
    for (const s of solutions) {
      for (const id of s.solves) edge(s.id, id, "solves");
      for (const id of s.partlySolves) edge(s.id, id, "partly");
      for (const id of s.needs) edge(id, s.id, "needs");
      for (const id of s.alternativeTo) if (s.id < id) edge(s.id, id, "alt");
    }
    return { nodes, edges };
  }

  const cssVar = (name) => getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  const isDark = () => cssVar("color-scheme") === "dark";

  function graphStyle() {
    const v = cssVar;
    const tint = isDark() ? 0.26 : 0.13;
    const statusStyle = (cls, color) => ({
      selector: `node.s-${cls}`,
      style: { "border-color": v(color), "background-color": v(color), "background-opacity": tint },
    });
    return [
      {
        selector: "node",
        style: {
          label: "data(label)",
          "text-wrap": "wrap",
          "text-valign": "center",
          "text-halign": "center",
          "font-family": "system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
          "font-size": 13,
          "min-zoomed-font-size": 7,
          "line-height": 1.25,
          color: v("--text"),
          width: "data(w)",
          height: "data(h)",
          shape: "round-rectangle",
          "background-color": v("--surface"),
          "border-width": 1.6,
          "border-color": v("--border"),
        },
      },
      { selector: "node.problem", style: { "text-max-width": "206px" } },
      { selector: "node.solution", style: { shape: "cut-rectangle", "text-max-width": "200px", "font-weight": 600, "border-width": 2.2 } },
      {
        selector: "node.req",
        style: { "text-max-width": "154px", "background-color": v("--surface-2"), "border-style": "dashed", "border-color": v("--muted") },
      },
      statusStyle("open", "--st-open"),
      statusStyle("decision", "--st-decision"),
      statusStyle("proposed", "--st-proposed"),
      statusStyle("resolved", "--st-resolved"),
      statusStyle("closed", "--st-closed"),
      {
        selector: "edge",
        style: {
          width: 1.6,
          "curve-style": "bezier",
          "target-arrow-shape": "triangle",
          "arrow-scale": 0.9,
          "line-color": v("--muted"),
          "target-arrow-color": v("--muted"),
          opacity: 0.75,
        },
      },
      { selector: "edge.cause", style: { width: 2.4, "line-color": v("--text"), "target-arrow-color": v("--text"), opacity: 0.6 } },
      { selector: "edge.part", style: { "line-style": "dotted", width: 2 } },
      { selector: "edge.solves", style: { width: 2.4, "line-color": v("--st-resolved"), "target-arrow-color": v("--st-resolved") } },
      { selector: "edge.partly", style: { "line-style": "dashed", width: 2, "line-color": v("--st-resolved"), "target-arrow-color": v("--st-resolved") } },
      { selector: "edge.needs", style: { "line-style": "dashed", width: 2, "line-color": v("--st-decision"), "target-arrow-color": v("--st-decision") } },
      {
        selector: "edge.alt",
        style: { "line-style": "dashed", width: 1.8, "target-arrow-shape": "none", "line-color": v("--st-decision"), "curve-style": "straight" },
      },
      { selector: "edge.affects", style: { width: 1, opacity: 0.28 } },
      { selector: "edge.blocks", style: { width: 2.6, "line-color": v("--st-open"), "target-arrow-color": v("--st-open"), opacity: 0.85 } },
      {
        selector: "edge.needed",
        style: { width: 2, "line-style": "dashed", "line-color": v("--sev-medium"), "target-arrow-color": v("--sev-medium"), opacity: 0.85 },
      },
      {
        selector: "node.goal",
        style: {
          shape: "round-octagon",
          "font-size": 15,
          "font-weight": 700,
          "text-max-width": "236px",
          "border-width": 3,
          "border-color": v("--accent"),
          "background-color": v("--accent"),
          "background-opacity": isDark() ? 0.3 : 0.14,
        },
      },
      { selector: ".faded", style: { opacity: 0.07 } },
      { selector: ".hidden", style: { display: "none" } },
      { selector: "edge.hl", style: { opacity: 0.95 } },
      { selector: "node.focus", style: { "border-width": 4.5, "border-color": v("--accent") } },
    ];
  }

  function buildGraph() {
    const el = document.getElementById("cy");
    if (!el) return;
    if (cy) {
      cy.destroy();
      cy = null;
    }
    if (!window.cytoscape) {
      el.innerHTML = '<p class="empty">The graph library could not be loaded (are you offline?). The other views still work.</p>';
      return;
    }
    const { nodes, edges } = graphElements();
    cy = window.cytoscape({
      container: el,
      elements: { nodes, edges },
      style: graphStyle(),
      wheelSensitivity: 0.25,
      minZoom: 0.06,
      maxZoom: 2.5,
      boxSelectionEnabled: false,
    });
    const layoutEles = cy.elements().not("edge.alt");
    try {
      layoutEles.layout({ name: "dagre", rankDir: "LR", nodeSep: 16, rankSep: 110, edgeSep: 8, ranker: "network-simplex", fit: true, padding: 30, animate: false }).run();
    } catch (e) {
      layoutEles.layout({ name: "breadthfirst", directed: true, fit: true, padding: 30 }).run();
    }
    fullPositions = {};
    cy.nodes().forEach((n) => {
      const p = n.position();
      fullPositions[n.id()] = { x: p.x, y: p.y };
    });
    cy.on("tap", "node", (e) => {
      location.hash = `#/g/${e.target.id()}`;
    });
    cy.on("tap", (e) => {
      if (e.target === cy) location.hash = "#/graph";
    });
    const tip = document.getElementById("gtip");
    if (tip) {
      cy.on("mouseover", "node", (e) => {
        const d = e.target.data();
        const p = e.target.renderedPosition();
        tip.innerHTML = `<strong>${esc(d.label.replace("\n", ": "))}</strong><span>${esc(d.tip || "")}</span>`;
        tip.style.left = `${Math.min(p.x + 14, el.clientWidth - 280)}px`;
        tip.style.top = `${p.y + 14}px`;
        tip.style.display = "block";
      });
      cy.on("mouseout", "node", () => {
        tip.style.display = "none";
      });
      cy.on("pan zoom tap", () => {
        tip.style.display = "none";
      });
    }
  }

  function capZoom() {
    if (cy && cy.zoom() > 1.2) cy.zoom({ level: 1.2, renderedPosition: { x: cy.width() / 2, y: cy.height() / 2 } });
  }

  function restoreFullLayout() {
    if (fullPositions) cy.nodes().positions((n) => fullPositions[n.id()] || n.position());
  }

  function highlight(id) {
    if (!cy) return;
    const n = id ? cy.getElementById(id) : null;
    cy.elements().removeClass("faded hl focus hidden");
    if (!n || n.empty()) {
      restoreFullLayout();
      cy.fit(undefined, 30);
      return;
    }
    let set = n;
    if (goal && id === goal.id) {
      // Everything is in the goal's way; show only the problems, so that it stays readable.
      const ps = n.union(n.predecessors().nodes(".problem"));
      set = ps.union(ps.edgesWith(ps));
    } else {
      if (gstate.mode !== "down") set = set.union(n.predecessors());
      if (gstate.mode !== "up") set = set.union(n.successors());
    }
    if (gstate.mode !== "up" && !(goal && id === goal.id)) {
      // also the solutions of everything it leads to: the whole plan downstream
      const sol = set.nodes(".problem").incomers("edge.solves, edge.partly");
      set = set.union(sol).union(sol.sources());
    }
    const alt = set.nodes(".solution").connectedEdges(".alt");
    set = set.union(alt).union(alt.connectedNodes());
    cy.elements().not(set).addClass(gstate.focus ? "hidden" : "faded");
    set.addClass("hl");
    n.addClass("focus");
    if (gstate.focus) {
      set
        .not("edge.alt")
        .layout({ name: "dagre", rankDir: "LR", nodeSep: 18, rankSep: 70, edgeSep: 8, fit: true, padding: 40, animate: false })
        .run();
      capZoom();
    } else {
      restoreFullLayout();
      cy.fit(set, 50);
      capZoom();
    }
  }

  function graphPanel(id) {
    if (goal && id === goal.id) return goalDetail(goal);
    if (id === "req-all") return allReqDetail();
    if (reqBySlug.has(id)) return reqDetail(reqBySlug.get(id));
    if (byId.has(id)) return itemDetail(id);
    return `<div class="placeholder"><h2>What affects what</h2>
      <p>Read the graph from left to right: <strong>solutions</strong> → the <strong>problems</strong> they solve → the problems those lead to → the <strong>requirements</strong> they affect.</p>
      <p>Click a node to see only what leads to it and what it leads to, laid out large enough to read, with its details here. Click the background to return to the full map. Hover a node to see its title; scroll to zoom, drag to move.</p>
      ${goal ? `<p><a href="#/g/${goal.id}"><strong>Start at the goal</strong></a>: everything that blocks the translation to the Event Calculus, and what solves it.</p>` : ""}
      <h3 class="sect">Start here: root causes</h3>
      ${rootCausesHtml((p) => `#/g/${p.id}`)}
      ${graphLegendHtml()}</div>`;
  }

  function graphLegendHtml() {
    return `<div class="glegend">
      <div><span class="gl-node problem"></span>Problem (colour = status)</div>
      <div><span class="gl-node solution"></span>Solution</div>
      <div><span class="gl-node req"></span>Requirement</div>
      <div><span class="gl-edge cause"></span>leads to</div>
      <div><span class="gl-edge part"></span>sub-problem</div>
      <div><span class="gl-edge solves"></span>solves</div>
      <div><span class="gl-edge partly"></span>solves in part</div>
      <div><span class="gl-edge needs"></span>is needed by</div>
      <div><span class="gl-edge alt"></span>alternatives</div>
      <div><span class="gl-edge affects"></span>affects</div>
      <div><span class="gl-node goal"></span>Goal</div>
      <div><span class="gl-edge blocks"></span>blocks the goal</div>
      <div><span class="gl-edge needed"></span>needed for the goal</div>
    </div>`;
  }

  function graphViewHtml() {
    const chk = (id, on, label) => `<label class="check"><input type="checkbox" id="${id}"${on ? " checked" : ""}> ${esc(label)}</label>`;
    return `<div class="graphview">
      <div class="gtoolbar">
        <input type="search" id="gq" placeholder="Find a node (Enter)" aria-label="Find a node">
        ${chk("g-sol", gstate.solutions, "Solutions")}
        ${chk("g-req", gstate.reqs, "Requirements")}
        ${chk("g-goal", gstate.goal, "EC goal")}
        ${chk("g-part", gstate.parts, "Sub-problem links")}
        ${chk("g-done", gstate.done, "Resolved, applied and closed")}
        ${chk("g-focus", gstate.focus, "Show only what is connected")}
        <select id="g-mode" aria-label="What to highlight">
          <option value="both"${gstate.mode === "both" ? " selected" : ""}>Highlight causes and effects</option>
          <option value="up"${gstate.mode === "up" ? " selected" : ""}>Highlight what leads to it</option>
          <option value="down"${gstate.mode === "down" ? " selected" : ""}>Highlight what it leads to</option>
        </select>
        <button class="btn" id="g-fit" type="button">Fit</button>
      </div>
      <div class="gsplit">
        <div class="gwrap"><div class="gcanvas" id="cy"></div><div class="gtip" id="gtip"></div></div>
        <aside class="pane gpanel" id="gpanel"></aside>
      </div>
    </div>`;
  }

  function renderGraph(sel) {
    graphLinks = true;
    if (app.dataset.view !== "graph") {
      app.dataset.view = "graph";
      app.innerHTML = graphViewHtml();
      buildGraph();
    }
    gselected = sel;
    highlight(sel);
    const panel = document.getElementById("gpanel");
    panel.innerHTML = graphPanel(sel);
    panel.scrollTop = 0;
  }

  // ------------------------------------------------------------------ render & route

  function setTab(view) {
    document.querySelectorAll(".tabs a").forEach((a) => a.classList.toggle("on", a.dataset.view === view));
  }

  function showDetail(html) {
    const d = document.getElementById("detail");
    if (!d) return;
    d.innerHTML = html;
    if (window.matchMedia("(max-width: 900px)").matches) {
      if (location.hash.split("/").length > 2) d.scrollIntoView({ block: "start" });
    } else {
      window.scrollTo(0, 0);
    }
  }

  function renderProblems(sel) {
    graphLinks = false;
    if (app.dataset.view !== "problems") {
      app.dataset.view = "problems";
      app.innerHTML = `<div class="split"><section class="pane left">${toolbarHtml()}<div id="tree"></div></section><section class="pane right" id="detail"></section></div>`;
    } else {
      document.getElementById("chips").innerHTML = chipsHtml();
      document.getElementById("reqsel").value = tstate.req;
      document.getElementById("ecsel").value = tstate.ec;
    }
    document.getElementById("tree").innerHTML = treeHtml(sel);
    showDetail(
      byId.has(sel)
        ? itemDetail(sel)
        : placeholder(
            "Problems",
            "Select a problem in the tree to see its explanation, an example, the proposed solutions, and the requirements and tests it affects. The small numbers next to a problem are the requirements it affects.",
            legendHtml()
          )
    );
  }

  function renderSolutions(sel) {
    graphLinks = false;
    const groups = SOL_KEYS.map((k) => {
      const list = solutions.filter((s) => s.status === k).sort(compareItems);
      if (!list.length) return "";
      return `<h3 class="sect pad">${dot({ kind: "solution", status: k })} ${esc(SOL_STATUS[k].label)} <span class="muted">${list.length}</span></h3>
        <ul class="sollist">${list
          .map((s) => {
            const n = s.solves.length + s.partlySolves.length;
            return `<li><a href="#/s/${s.id}" class="${s.id === sel ? "sel" : ""}"><span class="stitle">${esc(s.title)}</span><span class="scount" title="Problems it solves">${n}</span></a></li>`;
          })
          .join("")}</ul>`;
    }).join("");
    app.dataset.view = "solutions";
    app.innerHTML = `<div class="split"><section class="pane left">${groups}</section><section class="pane right" id="detail"></section></div>`;
    showDetail(
      byId.has(sel)
        ? solutionDetail(byId.get(sel))
        : placeholder(
            "Solutions",
            "Each solution is a concrete change to the formalism, the examples, the tests or the tools. Select one to see what it changes, which problems it solves, and what it needs first. The number next to a solution is how many problems it solves."
          )
    );
  }

  function renderRequirements(slug) {
    graphLinks = false;
    const list = `<ul class="reqlist">${reqs
      .map((r) => {
        const c = countBy(problems.filter((p) => affectsDirectly(p, r.id)));
        const pills = STATUS_KEYS.filter((k) => c[k])
          .map((k) => `<span class="pill st-${k}" title="${c[k]} ${esc(STATUS[k].label.toLowerCase())}">${c[k]}</span>`)
          .join("");
        return `<li><a href="#/r/${r.slug}" class="${r.slug === slug ? "sel" : ""}"><span class="rid">${esc(r.id)}</span><span class="rtitle">${esc(
          r.title
        )}</span><span class="pills">${pills}</span></a></li>`;
      })
      .join("")}</ul>`;
    app.dataset.view = "requirements";
    app.innerHTML = `<div class="split"><section class="pane left">${list}</section><section class="pane right" id="detail"></section></div>`;
    const r = reqBySlug.get(slug);
    showDetail(
      r
        ? reqDetail(r)
        : placeholder(
            "Requirements",
            "Select a requirement to see its original text, its formalisation, its test cases, the problems that affect it and the solutions that change it. The coloured numbers count its problems by status."
          )
    );
  }

  function route() {
    const hash = location.hash.replace(/^#\/?/, "");
    const [path, query] = hash.split("?");
    const parts = path.split("/").filter(Boolean).map(decodeURIComponent);
    const params = new URLSearchParams(query || "");
    if (params.has("status")) tstate.statuses = new Set(params.get("status").split(",").filter((s) => STATUS[s]));
    if (params.has("req")) tstate.req = params.get("req");
    if (params.has("ec")) tstate.ec = params.get("ec");
    const head = parts[0] || "";
    if (head === "g" || head === "graph") {
      setTab("graph");
      renderGraph(head === "g" ? parts[1] || "" : "");
    } else if (head === "p" || head === "problems") {
      setTab("problems");
      renderProblems(head === "p" ? parts[1] || "" : "");
    } else if (head === "s" || head === "solutions") {
      setTab("solutions");
      renderSolutions(head === "s" ? parts[1] || "" : "");
    } else if (head === "r" || head === "requirements") {
      setTab("requirements");
      renderRequirements(head === "r" ? parts[1] || "" : "");
    } else if (head === "overview") {
      setTab("overview");
      graphLinks = false;
      app.dataset.view = "overview";
      app.innerHTML = overviewHtml();
      window.scrollTo(0, 0);
    } else {
      setTab("ec");
      graphLinks = false;
      app.dataset.view = "ec";
      app.innerHTML = ecViewHtml();
      window.scrollTo(0, 0);
    }
  }

  // ------------------------------------------------------------------ events

  function refreshTree() {
    const tree = document.getElementById("tree");
    if (!tree) return;
    const m = location.hash.match(/^#\/p\/([^?]+)/);
    tree.innerHTML = treeHtml(m ? decodeURIComponent(m[1]) : "");
  }

  app.addEventListener("click", (e) => {
    const t = e.target.closest("[data-toggle],[data-status],#expand,#collapse,#g-fit");
    if (!t) return;
    if (t.id === "g-fit") {
      if (cy) cy.animate({ fit: { eles: cy.elements(":visible"), padding: 30 }, duration: 250 });
      return;
    }
    if (t.dataset.toggle) {
      const id = t.dataset.toggle;
      if (tstate.collapsed.has(id)) tstate.collapsed.delete(id);
      else tstate.collapsed.add(id);
    } else if (t.dataset.status) {
      const k = t.dataset.status;
      if (tstate.statuses.has(k)) tstate.statuses.delete(k);
      else tstate.statuses.add(k);
      document.getElementById("chips").innerHTML = chipsHtml();
    } else if (t.id === "expand") {
      tstate.collapsed.clear();
    } else if (t.id === "collapse") {
      for (const it of items) if (childrenOf(it.id).length) tstate.collapsed.add(it.id);
    }
    refreshTree();
  });

  app.addEventListener("input", (e) => {
    if (e.target.id === "q") {
      tstate.search = e.target.value.trim();
      refreshTree();
    }
  });

  app.addEventListener("keydown", (e) => {
    if (e.target.id !== "gq" || e.key !== "Enter" || !cy) return;
    const q = e.target.value.trim().toLowerCase();
    if (!q) return;
    const hit = cy.nodes().filter((n) => n.data("label").toLowerCase().includes(q));
    if (hit.nonempty()) location.hash = `#/g/${hit[0].id()}`;
  });

  app.addEventListener("change", (e) => {
    const id = e.target.id;
    if (id === "reqsel" || id === "ecsel") {
      if (id === "reqsel") tstate.req = e.target.value;
      else tstate.ec = e.target.value;
      refreshTree();
      return;
    }
    const keys = { "g-sol": "solutions", "g-req": "reqs", "g-goal": "goal", "g-part": "parts", "g-done": "done" };
    if (keys[id]) {
      gstate[keys[id]] = e.target.checked;
      buildGraph();
      highlight(gselected);
    } else if (id === "g-focus") {
      gstate.focus = e.target.checked;
      highlight(gselected);
    } else if (id === "g-mode") {
      gstate.mode = e.target.value;
      highlight(gselected);
    }
  });

  // ------------------------------------------------------------------ theme

  const themeBtn = document.getElementById("theme");
  let theme = "auto";
  try {
    theme = localStorage.getItem("problem-tree-theme") || "auto";
  } catch (e) {
    /* storage unavailable */
  }
  function applyTheme() {
    if (theme === "light" || theme === "dark") document.documentElement.dataset.theme = theme;
    else delete document.documentElement.dataset.theme;
    if (themeBtn) themeBtn.textContent = `Theme: ${theme[0].toUpperCase()}${theme.slice(1)}`;
    if (cy) cy.style(graphStyle());
  }
  if (themeBtn) {
    themeBtn.addEventListener("click", () => {
      theme = theme === "auto" ? "light" : theme === "light" ? "dark" : "auto";
      try {
        localStorage.setItem("problem-tree-theme", theme);
      } catch (e) {
        /* storage unavailable */
      }
      applyTheme();
    });
  }
  if (window.matchMedia) {
    window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", () => {
      if (cy) cy.style(graphStyle());
    });
  }
  applyTheme();

  const generated = document.getElementById("generated");
  if (generated) {
    generated.textContent = `${problems.length} problems · ${solutions.length} solutions · generated ${DATA.generated.replace("T", " ")}`;
  }

  window.addEventListener("hashchange", route);
  route();
})();
